language: python

python: 
  
  - "3.7"

cache: pip

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt

script:
  - coverage run  --source tests/api/v1 -m pytest -v

after_success:
  - coveralls